### ISSUE TITLE
Request Feature : SSO

### ISSUE THREAD

**Issue by Knightsepehr** [lmsace/lmsace-connect-woocommerce#1]
Hello 
I tried your plugin and its very nice 
it would make the plugin alot more usefull and better that you add sso feature
in a way that there would be a tab in my account in wordpress would be created like courses or something like that 
then the user would click  a link that would redirect them to their moodle course and they would be automatically signed in 
and wont need to sign in them selves

**Comment by prasanna-lmsace** [comment]
Hello @Knightsepehr ,

I am pleased to inform you that we have successfully implemented the Single Sign-On (SSO) feature and launched LMSACE Connect v2.0.

We believe this update will meet your requirements. To get started with the SSO and explore other features, please refer to the [documentation ](https://github.com/lmsace/lmsace-connect-woocommerce/wiki)provided.

If you have any questions or need assistance with the setup, feel free to reach out to us.

Thank you for your support.
